# Generated by Django 3.1.4 on 2020-12-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('image', models.ImageField(upload_to='director_images/')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('date_upload', models.DateField(auto_now_add=True)),
                ('synopsis', models.TextField()),
                ('video', models.FileField(upload_to='films/<django.db.models.fields.CharField>/video')),
                ('likes', models.IntegerField(default=0)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appMediaCenter.director')),
            ],
        ),
    ]
