# Generated by Django 3.1.4 on 2020-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMediaCenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(upload_to='media/director_images/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(upload_to='media/films/<django.db.models.fields.CharField>/video/'),
        ),
    ]
