# Generated by Django 3.1.4 on 2020-12-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMediaCenter', '0002_auto_20201206_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/films/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(upload_to='media/films/<django.db.models.fields.CharField>/'),
        ),
    ]
