# Generated by Django 3.1.4 on 2020-12-06 19:46

import appMediaCenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMediaCenter', '0004_auto_20201206_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=appMediaCenter.models.generatePath),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(upload_to=appMediaCenter.models.generatePath),
        ),
    ]
