# Generated by Django 3.1.4 on 2020-12-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMediaCenter', '0005_auto_20201206_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='folder',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
