# Generated by Django 3.1.4 on 2020-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMediaCenter', '0006_film_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='folder',
            field=models.CharField(default=models.CharField(max_length=50), max_length=20),
        ),
    ]
