# Generated by Django 3.1.4 on 2021-01-21 17:21

import appMediaCenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMediaCenter', '0008_auto_20201211_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='subtitle',
            field=models.FileField(blank=True, null=True, upload_to=appMediaCenter.models.generatePath),
        ),
    ]
